swagger: "2.0"
info:
    title: Books Service
    description: HTTP service for managing books
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        get:
            tags:
                - books
            summary: findAll books
            description: FindAll Books
            operationId: books#findAll
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksBookCollection'
            schemes:
                - http
        post:
            tags:
                - books
            summary: create books
            description: Create a new book.
            operationId: books#create
            consumes:
                - multipart/form-data
            parameters:
                - name: CreateRequestBody
                  in: formData
                  required: true
                  schema:
                    $ref: '#/definitions/BooksCreateRequestBody'
                    required:
                        - title
                        - author
                        - published_at
            responses:
                "201":
                    description: Created response.
                    schema:
                        type: string
            schemes:
                - http
    /books/{id}:
        get:
            tags:
                - books
            summary: findById books
            description: Find book by id
            operationId: books#findById
            parameters:
                - name: id
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksFindByIDResponseBody'
                        required:
                            - id
                            - title
                            - author
                            - published_at
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksFindByIDNotFoundResponseBody'
            schemes:
                - http
        put:
            tags:
                - books
            summary: update books
            description: Update a book.
            operationId: books#update
            consumes:
                - multipart/form-data
            parameters:
                - name: id
                  in: path
                  description: Book ID
                  required: true
                  type: integer
                - name: UpdateRequestBody
                  in: formData
                  required: true
                  schema:
                    $ref: '#/definitions/BooksUpdateRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksUpdateNotFoundResponseBody'
            schemes:
                - http
        delete:
            tags:
                - books
            summary: delete books
            description: Delete a book.
            operationId: books#delete
            parameters:
                - name: id
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksDeleteNotFoundResponseBody'
            schemes:
                - http
definitions:
    Book:
        title: 'Mediatype identifier: application/vnd.book+json; view=default'
        type: object
        properties:
            author:
                type: string
                description: Author of book
                example: Voluptate quo veritatis doloribus nesciunt.
            book_cover_bytes:
                type: string
                description: Image File base64
                example:
                    - 69
                    - 117
                    - 109
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 117
                    - 109
                    - 32
                    - 108
                    - 97
                    - 98
                    - 111
                    - 114
                    - 101
                    - 32
                    - 113
                    - 117
                    - 97
                    - 115
                    - 32
                    - 113
                    - 117
                    - 105
                    - 100
                    - 101
                    - 109
                    - 32
                    - 115
                    - 105
                    - 116
                    - 46
                format: byte
            book_cover_file_name:
                type: string
                description: Book cover file name
                example: Rerum illum vel qui totam incidunt aut.
            book_cover_file_type:
                type: string
                description: Book cover file type
                example: Mollitia error ratione delectus quas temporibus possimus.
            id:
                type: integer
                description: ID of book
                example: 8403090221909196608
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: Tempore amet provident velit voluptate et.
            title:
                type: string
                description: Title of book
                example: Amet dolores qui quam dolorem.
        description: A book payload (default view)
        example:
            author: Quasi in nemo.
            book_cover_bytes:
                - 68
                - 111
                - 108
                - 111
                - 114
                - 101
                - 109
                - 32
                - 101
                - 116
                - 46
            book_cover_file_name: Sunt a quae quo autem debitis exercitationem.
            book_cover_file_type: Sed vitae a amet distinctio reprehenderit ea.
            id: 6725158436612729976
            published_at: Porro assumenda recusandae corrupti quam doloribus similique.
            title: Voluptatibus voluptatem.
        required:
            - id
            - title
            - author
            - published_at
    BookResponseBody:
        title: 'Mediatype identifier: application/vnd.book+json; view=default'
        type: object
        properties:
            author:
                type: string
                description: Author of book
                example: Voluptas accusamus ut.
            book_cover_bytes:
                type: string
                description: Image File base64
                example:
                    - 86
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 109
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 109
                    - 32
                    - 117
                    - 116
                    - 32
                    - 101
                    - 120
                    - 32
                    - 101
                    - 116
                    - 32
                    - 113
                    - 117
                    - 97
                    - 115
                    - 105
                    - 46
                format: byte
            book_cover_file_name:
                type: string
                description: Book cover file name
                example: Qui et deleniti fugit est aut.
            book_cover_file_type:
                type: string
                description: Book cover file type
                example: Et enim odio voluptatum.
            id:
                type: integer
                description: ID of book
                example: 2408440651276625472
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: Consequatur quia consequatur et sed aut doloribus.
            title:
                type: string
                description: Title of book
                example: Possimus eos facere placeat.
        description: A book payload (default view)
        example:
            author: Fuga voluptatibus alias.
            book_cover_bytes:
                - 70
                - 117
                - 103
                - 105
                - 116
                - 32
                - 97
                - 117
                - 116
                - 32
                - 110
                - 111
                - 110
                - 32
                - 113
                - 117
                - 97
                - 115
                - 32
                - 101
                - 116
                - 32
                - 113
                - 117
                - 111
                - 115
                - 46
            book_cover_file_name: Delectus voluptatem tenetur eveniet earum.
            book_cover_file_type: Et error officiis.
            id: 8475285655639229824
            published_at: Minima dolorum.
            title: Quo aliquam sit sapiente numquam.
        required:
            - id
            - title
            - author
            - published_at
    BooksBookCollection:
        title: 'Mediatype identifier: application/vnd.book+json; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/Book'
        description: BookCollection is the result type for an array of Book (default view)
        example:
            - author: Eos consequuntur tempore.
              book_cover_bytes:
                - 69
                - 117
                - 109
                - 32
                - 109
                - 97
                - 105
                - 111
                - 114
                - 101
                - 115
                - 32
                - 109
                - 97
                - 120
                - 105
                - 109
                - 101
                - 46
              book_cover_file_name: Non dolores quasi saepe sunt est dolor.
              book_cover_file_type: Expedita commodi facere magni et.
              id: 4485231234075589164
              published_at: Est quibusdam rerum.
              title: At nesciunt deserunt.
            - author: Eos consequuntur tempore.
              book_cover_bytes:
                - 69
                - 117
                - 109
                - 32
                - 109
                - 97
                - 105
                - 111
                - 114
                - 101
                - 115
                - 32
                - 109
                - 97
                - 120
                - 105
                - 109
                - 101
                - 46
              book_cover_file_name: Non dolores quasi saepe sunt est dolor.
              book_cover_file_type: Expedita commodi facere magni et.
              id: 4485231234075589164
              published_at: Est quibusdam rerum.
              title: At nesciunt deserunt.
            - author: Eos consequuntur tempore.
              book_cover_bytes:
                - 69
                - 117
                - 109
                - 32
                - 109
                - 97
                - 105
                - 111
                - 114
                - 101
                - 115
                - 32
                - 109
                - 97
                - 120
                - 105
                - 109
                - 101
                - 46
              book_cover_file_name: Non dolores quasi saepe sunt est dolor.
              book_cover_file_type: Expedita commodi facere magni et.
              id: 4485231234075589164
              published_at: Est quibusdam rerum.
              title: At nesciunt deserunt.
            - author: Eos consequuntur tempore.
              book_cover_bytes:
                - 69
                - 117
                - 109
                - 32
                - 109
                - 97
                - 105
                - 111
                - 114
                - 101
                - 115
                - 32
                - 109
                - 97
                - 120
                - 105
                - 109
                - 101
                - 46
              book_cover_file_name: Non dolores quasi saepe sunt est dolor.
              book_cover_file_type: Expedita commodi facere magni et.
              id: 4485231234075589164
              published_at: Est quibusdam rerum.
              title: At nesciunt deserunt.
    BooksCreateRequestBody:
        title: BooksCreateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Omnis voluptate velit ratione sint voluptatibus quos.
            book_cover:
                $ref: '#/definitions/FileRequestBody'
            published_at:
                type: string
                description: Published date of the book
                example: "2024-01-27"
            title:
                type: string
                description: Title of the book
                example: Distinctio sed occaecati sequi veniam.
        example:
            author: Neque voluptas sequi soluta consequatur.
            book_cover:
                bytes:
                    - 73
                    - 110
                    - 32
                    - 114
                    - 101
                    - 109
                    - 32
                    - 110
                    - 111
                    - 110
                    - 46
                name: Architecto sapiente nesciunt aut repellendus rerum quia.
                type: Rerum enim quibusdam qui qui hic quia.
            published_at: "2024-01-27"
            title: Fuga est sed blanditiis et.
        required:
            - title
            - author
            - published_at
    BooksDeleteNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: delete_NotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksFindByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: findById_NotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksFindByIDResponseBody:
        title: BooksFindByIDResponseBody
        $ref: '#/definitions/BookResponseBody'
    BooksUpdateNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: update_NotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksUpdateRequestBody:
        title: BooksUpdateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Odit odio est ut est sit.
            book_cover:
                $ref: '#/definitions/FileRequestBody'
            published_at:
                type: string
                description: Published date of the book
                example: "2023-12-31"
            title:
                type: string
                description: Title of the book
                example: Et eum laborum dolore exercitationem.
        example:
            author: Illum consequatur voluptatem illo.
            book_cover:
                bytes:
                    - 73
                    - 110
                    - 32
                    - 114
                    - 101
                    - 109
                    - 32
                    - 110
                    - 111
                    - 110
                    - 46
                name: Architecto sapiente nesciunt aut repellendus rerum quia.
                type: Rerum enim quibusdam qui qui hic quia.
            published_at: "2023-12-31"
            title: Perferendis hic eos.
    FileRequestBody:
        title: FileRequestBody
        type: object
        properties:
            bytes:
                type: string
                example:
                    - 78
                    - 111
                    - 110
                    - 32
                    - 99
                    - 117
                    - 112
                    - 105
                    - 100
                    - 105
                    - 116
                    - 97
                    - 116
                    - 101
                    - 32
                    - 99
                    - 111
                    - 110
                    - 115
                    - 101
                    - 99
                    - 116
                    - 101
                    - 116
                    - 117
                    - 114
                    - 32
                    - 97
                    - 114
                    - 99
                    - 104
                    - 105
                    - 116
                    - 101
                    - 99
                    - 116
                    - 111
                    - 32
                    - 97
                    - 117
                    - 116
                    - 32
                    - 113
                    - 117
                    - 105
                    - 46
                format: byte
            name:
                type: string
                example: Distinctio labore optio incidunt dignissimos sed omnis.
            type:
                type: string
                example: Sed nihil fugit minima cupiditate.
        description: Image Upload Type
        example:
            bytes:
                - 81
                - 117
                - 105
                - 32
                - 97
                - 117
                - 116
                - 32
                - 100
                - 111
                - 108
                - 111
                - 114
                - 105
                - 98
                - 117
                - 115
                - 32
                - 101
                - 120
                - 112
                - 101
                - 100
                - 105
                - 116
                - 97
                - 32
                - 97
                - 117
                - 116
                - 101
                - 109
                - 32
                - 113
                - 117
                - 105
                - 115
                - 32
                - 105
                - 117
                - 115
                - 116
                - 111
                - 46
            name: Sit corrupti saepe laudantium qui eligendi.
            type: Id rem libero a sunt.
